[plugin]
name = "brainworm"
version = "0.3.0"
description = "DAIC workflow enforcement and development intelligence for Claude Code"
author = "Logan Smith"
repository = "https://github.com/lsmith090/cc-plugins"

[plugin.requirements]
claude_code_version = ">=0.1.0"
python_version = ">=3.12"

[plugin.dependencies]
# Python packages required by the plugin
packages = [
    "toml>=0.10.0",
    "rich>=13.0.0",
]

[plugin.hooks]
# Hooks provided by this plugin
session_start = "hooks/session_start.py"
pre_tool_use = "hooks/pre_tool_use.py"
post_tool_use = "hooks/post_tool_use.py"
user_prompt_submit = "hooks/user_prompt_submit.py"
stop = "hooks/stop.py"
subagent_stop = "hooks/subagent_stop.py"
session_end = "hooks/session_end.py"
pre_compact = "hooks/pre_compact.py"
notification = "hooks/notification.py"
raw_data_capture = "hooks/raw_data_capture.py"
transcript_processor = "hooks/transcript_processor.py"

[plugin.commands]
# Slash commands provided
daic = "commands/daic.md"
add-trigger = "commands/add-trigger.md"
api-mode = "commands/api-mode.md"

[plugin.agents]
# Specialized agents
code-review = "agents/code-review.md"
context-gathering = "agents/context-gathering.md"
context-refinement = "agents/context-refinement.md"
logging = "agents/logging.md"
service-documentation = "agents/service-documentation.md"
session-docs = "agents/session-docs.md"

[plugin.scripts]
# Utility scripts
create_task = "scripts/create_task.py"
update_daic_mode = "scripts/update_daic_mode.py"
view_analytics = "scripts/view_analytics.py"
statusline_script = "scripts/statusline-script.sh"
